config/routes.rb
Marcinha::Application.routes.draw do
  root :to => 'home#index'
    get 'portfolio' => 'home#portfolio'
    get 'fotografia' => 'home#fotografia'
    get 'editorial' => 'home#editorial'
    get 'contato' => 'home#contato'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'

	def index
	end

	def portfolio
	end

	def fotografia
	end

	def editorial
	end

	def contato
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contato.html.erb
<style type="text/css">
#box{
	
	width: 800px;
	height: 301px;

}
#contato {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	margin-left: 40px;
	float: left;
	border-radius: 10px;
	}

.text{
			font-family: "Arial"; 
			font-size: 19px; 
			color: #faf9f9;
			padding: 15px;
			text-align: left;
		}

#form {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	float: right;
	border-radius: 10px;		
}

.text2{
			font-family: "Arial"; 
			font-size: 19px; 
			color: #ee3680;
			padding: 15px;
			text-align: left;
		}


</style>

<div id="box">
	<div id="contato">
		<div class="text">
			<br>
			Caso tenha gostado de meus trabalhos e queira entrar em contato, você pode enviar por email ou mensagem.
			<br><br>
			marcinhagongora@gmail.com
			<br><br>
			Responderei o mais rápido possível.
		</div>	
	</div>

	<div id="form">
		<div class="text2">
			Nome
			<br>
			<input type="text" size="38">
			<br><br>
			Email
			<br>
			<input type="text" size="38">
			<br><br>
			Mensagem
			<br>
			<textarea name="mensagens" cols="30" rows="4"></textarea>
			<br>
			<input type="submit" title="Enviar" onClick="alert('Mensagem enviada com sucesso!'); window.location.reload()" style='margin-top: 5px;'>
		</div>
	</div>
</div>

app/views/home/editorial.html.erb
<style type="text/css">
#portfolio {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	margin-left: 40px;
	border-radius: 10px;
	float: left;
}

#box{
	width: 800px;
	height: 301px;
}

#form{
	width: 420px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	float: right;
	border-radius: 10px;		
}

.text{
	font-family:"Lucida Calligraphy";
	font-size: 22px;
	color: #ee3680;
	text-align: left;
	padding: 15px;
}

.black_overlay{
	display: none;
	position: absolute;
	top: 0%;
	left: 0%;
	width: 100%;
	height: 100%;
	background-color: black;
	z-index:1001;
	-moz-opacity: 0.8;
	opacity:.80;
	filter: alpha(opacity=80);
}
 
.white_content{
	display: none;
	position: absolute;
	top: 12%;
	left: 25%;
	width: 50%;
	height: 65%%;
	padding: 16px;
	border: 16px solid black;
	background-color: white;
	z-index:1002;
	overflow: auto;
}

.img1{	width: 180px;	height: 250px;  float: left; padding:10px 15px;}
.img2{	width: 180px;	height: 250px;  float: right; padding:10px 15px;}

.img_f{	width: 100%;}
</style>
<div id="box">
	<div id="portfolio">
		<div class="text">
			<br>
			<%= link_to "Cartazes", portfolio_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
			<br><br>
			<%= link_to "Fotografia", fotografia_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
			<br><br>
			<%= link_to "Editorial", editorial_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
		</div>	
	</div>
	
	<div id="form">
		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/capa.jpg" class= "img1"></a></p>
		<div id="light1" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/capa.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>

		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/capa2.jpg" class= "img2"></a></p>
		<div id="light2" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/capa2.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>
	</div>
</div>

app/views/home/fotografia.html.erb
<style type="text/css">
#portfolio {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	margin-left: 40px;
	border-radius: 10px;
	float: left;
}

#box{
	width: 800px;
	height: 301px;
}

#form{
	width: 420px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	float: right;
	border-radius: 10px;		
}

.text{
	font-family:"Lucida Calligraphy";
	font-size: 22px;
	color: #ee3680;
	text-align: left;
	padding: 15px;
}

.black_overlay{
	display: none;
	position: absolute;
	top: 0%;
	left: 0%;
	width: 100%;
	height: 100%;
	background-color: black;
	z-index:1001;
	-moz-opacity: 0.8;
	opacity:.80;
	filter: alpha(opacity=80);
}
 
.white_content{
	display: none;
	position: absolute;
	top: 12%;
	left: 25%;
	width: 50%;
	height: 65%%;
	padding: 16px;
	border: 16px solid black;
	background-color: white;
	z-index:1002;
	overflow: auto;
}

.img1{	width: 150px;	height: 125px; padding: 1px 0 0 50px; float: left;}
.img2{	width: 150px;	height: 125px; padding: 1px 45px 0 0; float: right;}
.img3{	width: 150px;	height: 125px; padding: 15px 15px 0 50px; float: left;}

.img_f{	width: 100%;	height: 100%;}
</style>
<div id="box">
	<div id="portfolio">
		<div class="text">
			<br>
			<%= link_to "Cartazes", portfolio_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
			<br><br>
			<%= link_to "Fotografia", fotografia_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
			<br><br>
			<%= link_to "Editorial", editorial_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
		</div>	
	</div>

	<div id="form">
		<div id="form">
		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/pic1.jpg" class= "img1"></a></p>
		<div id="light1" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/pic1.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>

		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/pic2.jpg" class= "img2"></a></p>
		<div id="light2" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/pic2.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>

		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light3').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/pic3.jpg" class= "img3"></a></p>
		<div id="light3" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light3').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/pic3.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>
	</div>
</div>

	</div>
</div>

app/views/home/index.html.erb
<style type="text/css">
#home {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	margin-left: 40px;
	border-radius: 10px; 
}

.text{
		font-family: "Arial"; 
		font-size: 19px; 
		color: #faf9f9;
		padding: 15px;
		text-align: left;
	}

</style>
<div id="home">
	<div class="text">
		<br>
		Meu nome é Marcia, tenho 22 anos e curso designer gráfico na Uniso Sorocaba.
		<br><br>
		Tenho conhecimento em Ilustrator, Corel Draw, Photoshop, Blender e Indesign.
		<br><br>
		Amo arte, tecnologia e games.
	</div>	
</div>

app/views/home/portfolio.html.erb
<style type="text/css">
#portfolio {
	width: 300px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	margin-left: 40px;
	border-radius: 10px;
	float: left;
}

#box{
	width: 800px;
	height: 301px;
}

#form{
	width: 420px;
	height: 300px;
	border: 1px solid #ee3680;
	background-color: #1e1b1c;
	float: right;
	border-radius: 10px;		
}

.text{
	font-family:"Lucida Calligraphy";
	font-size: 22px;
	color: #ee3680;
	text-align: left;
	padding: 15px;
}

.black_overlay{
	display: none;
	position: absolute;
	top: 0%;
	left: 0%;
	width: 100%;
	height: 100%;
	background-color: black;
	z-index:1001;
	-moz-opacity: 0.8;
	opacity:.80;
	filter: alpha(opacity=80);
}
 
.white_content{
	display: none;
	position: absolute;
	top: 12%;
	left: 25%;
	width: 50%;
	height: 65%%;
	padding: 16px;
	border: 16px solid black;
	background-color: white;
	z-index:1002;
	overflow: auto;
}

.img1{	width: 125px;	height: 125px; padding: 1px 0 0 50px; float: left;}
.img2{	width: 125px;	height: 125px; padding: 1px 70px 0 0; float: right;}
.img3{	width: 125px;	height: 125px; padding: 15px 15px 0 50px; float: left;}

.img_f{	width: 100%;}
</style>
<div id="box">
	<div id="portfolio">
		<div class="text">
			<br>
			<%= link_to "Cartazes", portfolio_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
			<br><br>
			<%= link_to "Fotografia", fotografia_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
			<br><br>
			<%= link_to "Editorial", editorial_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
		</div>	
	</div>
	<div id="form">
		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/nomes.jpg" class= "img1"></a></p>
		<div id="light1" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light1').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/nomes_f.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>

		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/m.jpg" class= "img2"></a></p>
		<div id="light2" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light2').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/m.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>

		<p><a href = "javascript:void(0)" onclick = "document.getElementById('light3').style.display='block';document.getElementById('fade').style.display='block'"><img src= "image/tipo.jpg" class= "img3"></a></p>
		<div id="light3" class="white_content"><a href = "javascript:void(0)" onclick = "document.getElementById('light3').style.display='none';document.getElementById('fade').style.display='none'"><img src= "image/tipo_f.jpg" class= "img_f"></a></div>
		<div id="fade" class="black_overlay"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marcinha</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>Marcia Gongora - Designer</title>
        <style type="text/css">
            #background {background-color: black;}
            #center     {background: url("/image/bg.jpg") repeat-y 0px 90px; width: 960px; height: 500px; margin: auto;}
            #top		{background: url("/image/logo.png"); width:312px; height:170px; margin-left: 40px;}
            #bottom		{background-color: #1e1b1c; width: 960px; height: 80px; margin: auto;}
            #link       {font-family:"Lucida Calligraphy"; font-size: 22px; color: #ee3680; padding: 10px 0 0 30px;}
            .home    {color: #faf9f9;}
        </style>
    </head>
    <body id="background">
		<div id="center">
			<div id="top"></div>
            <%= yield %>
		</div>
		<div id="bottom">
            <div id="link">
                <% if current_page?(:action => 'index') %>
                    <%= link_to "Home", root_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
                <% else %>
                    <%= link_to "Home", root_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;'%>
                <% end%>

                <% if current_page?(:action => 'portfolio') or current_page?(:action => 'fotografia') or current_page?(:action => 'editorial') %>
                    <%= link_to "Portfólio", portfolio_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
                <% else %>
                    <%= link_to "Portfólio", portfolio_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;'%>
                <% end%>

                <% if current_page?(:action => 'contato') %>
                    <%= link_to "Contato", contato_path, :style => 'text-decoration: none; color: #faf9f9; padding-left:10px;' %>
                <% else %>
                    <%= link_to "Contato", contato_path, :style => 'text-decoration: none; color: #ee3680; padding-left:10px;' %>
                <% end%>
            </div>
        </div>